# Generated by Django 4.1.7 on 2023-05-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Attraction name"),
                ),
                ("price", models.IntegerField(verbose_name="Attraction price")),
                (
                    "description",
                    models.CharField(
                        max_length=250, verbose_name="Attraction description"
                    ),
                ),
                (
                    "address",
                    models.TextField(verbose_name="Attraction localization address"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Category name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Country name")),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Discount name"),
                ),
                ("value", models.IntegerField(verbose_name="Discount value in %")),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Discount description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Tour name")),
                ("duration", models.IntegerField(verbose_name="Tour Duration (days)")),
                ("price", models.IntegerField(verbose_name="Tour price")),
                ("attractions", models.ManyToManyField(to="local_guide.attraction")),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Booking price")),
                ("start_date", models.DateField(verbose_name="Booking start data")),
                ("adults_no", models.IntegerField(verbose_name="Number of adults")),
                ("kids_no", models.IntegerField(verbose_name="Number of kids")),
                ("seniors_no", models.IntegerField(verbose_name="Number of seniors")),
                (
                    "attraction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="local_guide.attraction",
                    ),
                ),
                (
                    "tour_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="local_guide.tour",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attraction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="local_guide.category"
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="local_guide.country"
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="local_guide.discount"
            ),
        ),
    ]
