# Generated by Django 4.1.7 on 2023-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_guide", "0002_alter_attraction_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="attraction", name="discount",),
        migrations.AddField(
            model_name="attraction",
            name="discounts",
            field=models.ManyToManyField(
                blank=True, null=True, to="local_guide.discount"
            ),
        ),
    ]
