# Generated by Django 4.1.7 on 2023-05-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_guide", "0004_alter_attraction_discounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Attraction description",
            ),
        ),
    ]
