# Generated by Django 4.1.7 on 2023-05-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("local_guide", "0005_alter_attraction_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="attraction_id",),
        migrations.RemoveField(model_name="booking", name="tour_id",),
        migrations.AddField(
            model_name="booking",
            name="tour_or_attraction_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="local_guide.attraction",
            ),
        ),
    ]
