# Generated by Django 4.1.7 on 2023-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "local_guide",
            "0006_remove_booking_attraction_id_remove_booking_tour_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="adults_no",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of adults"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="kids_no",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of kids"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="seniors_no",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of seniors"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateTimeField(verbose_name="Booking start data"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tour_or_attraction_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Tour(T) or attraction(A) id",
            ),
        ),
    ]
