# Generated by Django 4.1.7 on 2023-05-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("local_guide", "0007_alter_booking_adults_no_alter_booking_kids_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="local_guide.country",
            ),
        ),
    ]
