# Generated by Django 4.1.7 on 2023-05-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("local_guide", "0008_tour_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="local_guide.country"
            ),
        ),
    ]
