# Generated by Django 4.1.7 on 2023-05-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_guide", "0009_alter_tour_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="psp_checkout_id",
            field=models.IntegerField(null=True, verbose_name="Transaction ID"),
        ),
        migrations.AddField(
            model_name="booking",
            name="psp_id",
            field=models.IntegerField(null=True, verbose_name="PSP ID"),
        ),
        migrations.AddField(
            model_name="tour",
            name="attractions_no",
            field=models.IntegerField(
                null=True, verbose_name="Number of attractions in the tour"
            ),
        ),
    ]
