# Generated by Django 4.1.7 on 2023-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_guide", "0010_booking_psp_checkout_id_booking_psp_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="name",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Attraction name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Category name"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Country name"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Discount name"
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="name",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Tour name"
            ),
        ),
    ]
